spring:
  application:
    name: bank-backend
  datasource:
    url: jdbc:h2:mem:bankdb;DB_CLOSE_DELAY=-1
    username: test
    password: password122
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master.yaml
